ci: auto determine mafia version and build

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,8 +2,6 @@
 
 name: CI
 env:
-  MAFIA_BUILD: "1938"
-  MAFIA_VERSION: "20430"
   SCRIPT_NAMES: "autoscend.ash auto_pre_adv.ash auto_post_adv.ash auto_choice_adv.ash relay_autoscend.ash autoscend_settings_extra.ash"
 
 on: [push, pull_request]
@@ -17,16 +15,27 @@ jobs:
     - uses: actions/checkout@v2
 
     - name: Setup Java JDK
-      uses: actions/setup-java@v1.3.0
+      uses: actions/setup-java@v1.4.3
       with:
         java-version: 1.8
 
     - name: Prepare KoLmafia
       run: |
-        if [[ ! -f ".github/kolmafia.jar" ]]; then
-          curl "https://ci.kolmafia.us/job/Kolmafia/${MAFIA_BUILD}/artifact/dist/KoLmafia-${MAFIA_VERSION}.jar" --output .github/kolmafia.jar
+        set -o pipefail
+        export MAFIA_VERSION=$(head -n1 RELEASE/scripts/autoscend.ash | grep -o '[0-9]\+')
+        if [[ -z "$MAFIA_VERSION" ]]; then
+          echo "Couldn't determine required mafia version!"
+          exit 1
         fi
-    
+        export MAFIA_BUILD=$(curl --fail --silent --globoff 'https://ci.kolmafia.us/job/Kolmafia/api/json?tree=builds[number,artifacts[relativePath]]' | jq '[.builds[]] | map(select(.artifacts[].relativePath | contains(env.MAFIA_VERSION))) | .[] | .number' | head -n1)
+        if [[ -z "$MAFIA_BUILD" ]]; then
+          echo "Couldn't determine Jenkins build number!"
+          exit 1
+        fi
+        JENKINS_URL="https://ci.kolmafia.us/job/Kolmafia/${MAFIA_BUILD}/artifact/dist/KoLmafia-${MAFIA_VERSION}.jar"
+        echo "$JENKINS_URL"
+        curl "$JENKINS_URL" --output .github/kolmafia.jar
+
     - name: Install and verify
       run: |
         cd RELEASE
